/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f8f9ff",
        "on-primary": "#ffffff",
        "surface-container-highest": "#d9e3f6",
        "inverse-surface": "#27313f",
        "on-primary-fixed-variant": "#005323",
        secondary: "#2e6a41",
        "error-container": "#ffdad6",
        surface: "#f8f9ff",
        "on-secondary-container": "#347047",
        "surface-container-high": "#dee9fc",
        "on-secondary-fixed-variant": "#12512c",
        "on-background": "#121c2a",
        "on-primary-fixed": "#00210a",
        "tertiary-fixed": "#7ffc97",
        "on-surface-variant": "#3f493f",
        "inverse-primary": "#79db8d",
        "tertiary-container": "#008137",
        "secondary-container": "#b1f2be",
        "kvb-red": "#DC2626",
        "surface-tint": "#006d30",
        "on-tertiary-fixed-variant": "#005320",
        primary: "#00652c",
        "surface-container-low": "#eff4ff",
        "surface-dim": "#d0dbed",
        "surface-clinical": "#FFFFFF",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#96d5a3",
        "on-error-container": "#93000a",
        "secondary-fixed": "#b1f2be",
        "on-surface": "#121c2a",
        "on-tertiary-container": "#d4ffd4",
        outline: "#6f7a6e",
        error: "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#00210d",
        "outline-variant": "#becabc",
        "border-hairline": "#E2E8F0",
        "primary-fixed": "#95f8a7",
        "primary-container": "#15803d",
        "tertiary-fixed-dim": "#62df7d",
        "kvb-gold": "#CA8A04",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#d3ffd5",
        "surface-tinted": "#F0FDF4",
        "on-tertiary": "#ffffff",
        "border-accent": "#86EFAC",
        "surface-subtle": "#F8FAFC",
        "on-tertiary-fixed": "#002109",
        tertiary: "#006529",
        "primary-fixed-dim": "#79db8d",
        "surface-bright": "#f8f9ff",
        "surface-container": "#e6eeff",
        "surface-variant": "#d9e3f6"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        gutter: "1.5rem",
        "margin-mobile": "1.25rem",
        "space-sm": "0.5rem",
        "gutter-mobile": "1rem",
        "space-md": "1rem",
        "space-2xl": "4rem",
        margin: "3rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        display: ["Montserrat", "sans-serif"],
        sans: ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-xl-mobile": ["Montserrat", "sans-serif"],
        "label-sm": ["Montserrat", "sans-serif"],
        "body-sm": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "label-md": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "label-lg": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-xl-mobile": ["26px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "800" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "700" }]
      }
    }
  },
  plugins: []
};
